### ISSUE TITLE
where is the *_result.npz file

### ISSUE THREAD

**Issue by ChunmianLin** [Cogito2012/UString#1]
Hi, thanks for your work. 
When I run demo.py, it occurs the error message 'no 000821_result.npz file'.  I follow your instruction to prepare the dataset and pretrained model, but I really don't find the result file. 
Please help me!
Thanks in advance.

**Comment by ChunmianLin** [comment]
Many thanks, and I would further check the code you mentioned.

**Comment by monjurulkarim** [comment]
I want to run the demo.py for feature extraction, inference, and visualization. So, I didn't create the mmlab environment. However, when I run the demo.py file it is showed me "No module named "mmdet". So I pip installed mmdet.  Then it was showing "AttributeError: module 'mmcv' has no attribute '__version__'
So, I was trying to pip install mmcv-full. But it is showing " failed to build mmcv-full". How can I solve?

**Comment by Cogito2012** [comment]
@monjurulkarim Thanks for your interest in this work!
If you need to run demo.py for feature extraction, the mmdetection env `mmlab` is required. Recently I noticed that official mmdetection and mmcv-full are newer than what I used in this repo. So, to install `mmlab` env, you need to install mmcv-full==1.1.1, and checkout the tag v1.1.0 for mmdetection source code. You can refer to the following steps, which are also updated to the instructions in the README:

`shell
# create python environment
conda create -n mmlab python=3.7

# activate environment
conda activate mmlab

# install dependencies
pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
pip install mmcv-full==1.1.1

# Follow the instructions at https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
git checkout v1.1.0  # important!
cp -r ../Cascade\ R-CNN/* ./  # copy the downloaded files into mmdetection folder

# compile & install
pip install -v -e .
python setup.py install

`

**Comment by monjurulkarim** [comment]
Thank you for your help.
I have followed your instruction. Now I am getting the following error:
![image](https://user-images.githubusercontent.com/40798690/92840104-b7b25c00-f3ae-11ea-98f8-5e5739e31991.png)

**Comment by Cogito2012** [comment]
> Thank you for your help.
> I have followed your instruction. Now I am getting the following error:
> ![image](https://user-images.githubusercontent.com/40798690/92840104-b7b25c00-f3ae-11ea-98f8-5e5739e31991.png)
> 
> Do have idea why this is happening?
> Thanks

It seems that your installed torch-scatter is not compatible with the other torch libs. You can type `pip list | grep torch` in `py37` env, and see if these libs are correct:

```
torch                 1.2.0                
torch-cluster         1.4.5                
torch-geometric       1.3.2                
torch-scatter         1.4.0                
torch-sparse          0.4.3                
torchstat             0.0.7                
torchsummaryX         1.3.0                
torchvision           0.4.0a0+6b959ee
```

**Comment by monjurulkarim** [comment]
Thanks for your quick response.
My torch list are these:
![image](https://user-images.githubusercontent.com/40798690/92842063-18db2f00-f3b1-11ea-897e-891f8167992c.png)

Is this a problem?

**Comment by Cogito2012** [comment]
> Thanks for your quick response.
> My torch list are these:
> ![image](https://user-images.githubusercontent.com/40798690/92842063-18db2f00-f3b1-11ea-897e-891f8167992c.png)
> 
> Is this a problem?

It should be OK. But if your problem still appears, it could be possibly related to your compiler/OS environment, e.g., gcc/g++. I also noticed that `caffe` appears in your bug hint, which may provide cues to the solution.

**Comment by monjurulkarim** [comment]
@Cogito2012 Thank you! I'll try to fix it. 
I badly need to run your code. My professor is pushing me hard :(.

**Comment by monjurulkarim** [comment]
@Cogito2012 
Hi, what does v1.1.0 represent in "git checkout v1.1.0"? Is it the version number of mmdetection?

**Comment by monjurulkarim** [comment]
@Cogito2012 
Hey, I fixed the torch-scatter issue. You were right, there was mix-up between multiple version of torch.
Now I am facing the following problem:
![image](https://user-images.githubusercontent.com/40798690/93030019-c9357700-f5ed-11ea-9006-99e4706c031c.png)

**Comment by monjurulkarim** [comment]
@Cogito2012 
Now I am facing TypeError: __init__() got an unexpected keyword argument 'num_stages'

The Traceback is the following:
(base) mmoniruzzama@u108100:~/Monjurul/UString$ bash run_demo.sh demo/000821.mp4
Run feature extraction...
Traceback (most recent call last):
  File "demo.py", line 331, in <module>
    detector = init_detector(cfg_file, model_file, device=device)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'num_stages'
Saved in: demo/000821_feature.npz
Run accident inference...
Traceback (most recent call last):
  File "demo.py", line 339, in <module>
    from src.Models import UString
  File "/data/home/stufs1/mmoniruzzama/Monjurul/UString/src/Models.py", line 10, in <module>
    from torch_geometric.utils import remove_self_loops, add_self_loops
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.transforms
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/__init__.py", line 37, in <module>
    from .gdc import GDC
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/gdc.py", line 2, in <module>
    import numba
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/__init__.py", line 45, in <module>
    import numba.typed
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/typeddict.py", line 18, in <module>
    @njit
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 224, in njit
    return jit(*args, **kws)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 161, in jit
    return wrapper(pyfunc)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 177, in wrapper
    **dispatcher_args)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/dispatcher.py", line 576, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/utils.py", line 381, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/base.py", line 250, in __init__
    self.init()
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/cpu.py", line 49, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 612, in __init__
    self._init(self._llvm_module)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 621, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
Saved in: demo/000821_result.npz
Run result visualization...
Traceback (most recent call last):
  File "demo.py", line 353, in <module>
    all_results = np.load(p.result_file, allow_pickle=True)
  File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'demo/000821_result.npz'
Saved in: demo/000821_vis.avi

**Comment by Cogito2012** [comment]
@monjurulkarim It seems that you are using an incorrect version of mmdetection. This repo currently only supports for [`mmdetection==1.1.0`](https://github.com/open-mmlab/mmdetection/tree/v1.1.0). Please make sure you are following every step in README instruction.

**Comment by monjurulkarim** [comment]
@Cogito2012  Thank you for your reply. My CUDA version is 10.2. Seems like mmdetection==1.1.0 will not work on CUDA 10.2.

**Comment by Cogito2012** [comment]
@monjurulkarim Thanks for reporting this issue. There are some alternatives you may consider:

- Install both CUDA 10.0 and 10.2, and specify the CUDA_HOME variable to CUDA 10.0 only for this repo. Then, you can completely run the code in this repo.
- Train your own object detector, and replace the [line 111](https://github.com/Cogito2012/UString/blob/584044a03bca6e06f6691d9f2e91ee5023366e46/demo.py#L111) in demo.py. This will help you to obtain reasonable results but they may slightly different from our results.
- Directly download our provided feature files, and skip the object detection and feature extraction steps.

As I'm busy recently, I will try to update this repo to support the latest mmdetection and CUDA in the future. This will be not easy as those torch-related packages are dependent on lower version of pytorch, which is not compatible with CUDA 10.2 or higher version. You can also do it by yourself if you are interested. :-)

**Comment by monjurulkarim** [comment]
@Cogito2012 
Thank you very much for your help.
Option # 1 worked for me.

**Comment by monjurulkarim** [comment]
@Cogito2012 
For the option # 2, if I want to detect object and extract features with another pre-trained object detector (eg. faster rcnn/ Yolo v3, etc.)  from mmdetection where do I have to make changes?

**Comment by Cogito2012** [comment]
@monjurulkarim You will just need to use your pretrained detector to get bounding boxes, like what I did in [line 111](https://github.com/Cogito2012/UString/blob/584044a03bca6e06f6691d9f2e91ee5023366e46/demo.py#L111). Note that the bounding boxes should be 5-dims (x1, y1, x2, y2, score).
